### ISSUE TITLE
Auto saving while cooking

### ISSUE THREAD

**Issue by Eninxiseno** [GruffCassquatch/ClothingTweaker#1]
I noticed after updating that this mod alone causes an auto-save when one passes time while cooking. TLD is updated, as is this mod, and only Modsettings was active along side. The Moose Cloak was the only altered gear.

P.s- Thank you for sacrificing your time to create such mods and deliver to the community all that's missing.

**Comment by GruffCassquatch** [comment]
Hi, a new version that's better optimised will be coming out sometime soon (as a modding community we're working on a way to optimise these types of mods). It's possible the autosave is because of this issue, but I won't be able to know for sure until I make the next version and can test it.

**Comment by Eninxiseno** [comment]
Thank you for replying and for your diligence. This mod is lovely.

**Comment by GruffCassquatch** [comment]
I have published a pre-release of the new, optimised version. If you would like to test it out, I would appreciate your feedback!

**Comment by Eninxiseno** [comment]
However I can help out, I'm in.

**Comment by Eninxiseno** [comment]
> I have published a pre-release of the new, optimised version. If you would like to test it out, I would appreciate your feedback!

Works as it should. No auto-saving while passing time when cooking, and notably less lag. Very well done. Thank you so much. You're lovely.

**Comment by GruffCassquatch** [comment]
That's excellent news! Thank you so much for reporting the issue and testing the update, it's really very helpful. I will release 2.0 later today (Australia time).

If you're interested, come join The Long Dark Modding community on Discord for mod discussion, development, suggestions, troubleshooting, etc: https://discord.gg/QvFE7VV4WZ
